export const words = [
    {
        "Infinitive": "abide",
        "SimplePast": "abode",
        "PastParticiple": "abode",
        "Μετάφραση": "μένω, κατοικώ"
    }, {
        "Infinitive": "be",
        "SimplePast": "was, were",
        "PastParticiple": "been",
        "Μετάφραση": "είμαι"
    }, {
        "Infinitive": "bear",
        "SimplePast": "bore",
        "PastParticiple": "born, borne",
        "Μετάφραση": "αντέχω"
    }, {
        "Infinitive": "beat",
        "SimplePast": "beat",
        "PastParticiple": "beaten",
        "Μετάφραση": "δέρνω"
    }, {
        "Infinitive": "begin",
        "SimplePast": "began",
        "PastParticiple": "begun",
        "Μετάφραση": "αρχίζω"
    }, {
        "Infinitive": "bend",
        "SimplePast": "bent",
        "PastParticiple": "bent",
        "Μετάφραση": "κάμπτω"
    }, {
        "Infinitive": "bereave",
        "SimplePast": "bereft",
        "PastParticiple": "bereft",
        "Μετάφραση": "στερώ"
    }, {
        "Infinitive": "beseech",
        "SimplePast": "besought",
        "PastParticiple": "besought",
        "Μετάφραση": "ικετεύω"
    }, {
        "Infinitive": "bet",
        "SimplePast": "bet",
        "PastParticiple": "bet",
        "Μετάφραση": "στοιχηματίζω"
    }, {
        "Infinitive": "bid",
        "SimplePast": "bid",
        "PastParticiple": "bid",
        "Μετάφραση": "πλειοδοτώ"
    }, {
        "Infinitive": "bind",
        "SimplePast": "bound",
        "PastParticiple": "bound",
        "Μετάφραση": "δεσμεύω"
    }, {
        "Infinitive": "bite",
        "SimplePast": "bit",
        "PastParticiple": "bitten",
        "Μετάφραση": "δαγκώνω"
    }, {
        "Infinitive": "bleed",
        "SimplePast": "bled",
        "PastParticiple": "bled",
        "Μετάφραση": "αιμορραγώ"
    }, {
        "Infinitive": "blow",
        "SimplePast": "blew",
        "PastParticiple": "blown",
        "Μετάφραση": "φυσώ"
    }, {
        "Infinitive": "break",
        "SimplePast": "broke",
        "PastParticiple": "broken",
        "Μετάφραση": "σπάζω"
    }, {
        "Infinitive": "breed",
        "SimplePast": "bred",
        "PastParticiple": "bred",
        "Μετάφραση": "ανατρέφω"
    }, {
        "Infinitive": "bring",
        "SimplePast": "brought",
        "PastParticiple": "brought",
        "Μετάφραση": "φέρω"
    }, {
        "Infinitive": "build",
        "SimplePast": "built",
        "PastParticiple": "built",
        "Μετάφραση": "οικοδομώ"
    }, {
        "Infinitive": "burn",
        "SimplePast": "burned, burnt",
        "PastParticiple": "burned, burnt",
        "Μετάφραση": "καίω"
    }, {
        "Infinitive": "burst",
        "SimplePast": "burst",
        "PastParticiple": "burst",
        "Μετάφραση": "εκρηγνύομαι"
    }, {
        "Infinitive": "buy",
        "SimplePast": "bought",
        "PastParticiple": "bought",
        "Μετάφραση": "αγοράζω"
    }, {
        "Infinitive": "cast",
        "SimplePast": "cast",
        "PastParticiple": "cast",
        "Μετάφραση": "διανέμω ρόλους"
    }, {
        "Infinitive": "catch",
        "SimplePast": "caught",
        "PastParticiple": "caught",
        "Μετάφραση": "συλλαμβάνω"
    }, {
        "Infinitive": "chide",
        "SimplePast": "chide",
        "PastParticiple": "chidden",
        "Μετάφραση": "μαλώνω"
    }, {
        "Infinitive": "choose",
        "SimplePast": "chose",
        "PastParticiple": "chosen",
        "Μετάφραση": "επιλέγω"
    }, {
        "Infinitive": "cleave",
        "SimplePast": "cleft",
        "PastParticiple": "cleft",
        "Μετάφραση": "σχίζω"
    }, {
        "Infinitive": "cling",
        "SimplePast": "clung",
        "PastParticiple": "clung",
        "Μετάφραση": "προσκολλώ"
    }, {
        "Infinitive": "clothe",
        "SimplePast": "clad",
        "PastParticiple": "clad",
        "Μετάφραση": "ντύνω"
    }, {
        "Infinitive": "come",
        "SimplePast": "came",
        "PastParticiple": "come",
        "Μετάφραση": "έρχομαι"
    }, {
        "Infinitive": "cost",
        "SimplePast": "cost",
        "PastParticiple": "cost",
        "Μετάφραση": "κοστίζω"
    }, {
        "Infinitive": "creep",
        "SimplePast": "crept",
        "PastParticiple": "crept",
        "Μετάφραση": "έρπω"
    }, {
        "Infinitive": "crow",
        "SimplePast": "crew",
        "PastParticiple": "crowed",
        "Μετάφραση": "κρώζω"
    }, {
        "Infinitive": "cut",
        "SimplePast": "cut",
        "PastParticiple": "cut",
        "Μετάφραση": "κόβω"
    }, {
        "Infinitive": "dare",
        "SimplePast": "dared",
        "PastParticiple": "dared",
        "Μετάφραση": "τολμώ"
    }, {
        "Infinitive": "deal",
        "SimplePast": "dealt",
        "PastParticiple": "dealt",
        "Μετάφραση": "μεταχειρίζομαι"
    }, {
        "Infinitive": "dig",
        "SimplePast": "dug",
        "PastParticiple": "dug",
        "Μετάφραση": "σκάβω"
    }, {
        "Infinitive": "do",
        "SimplePast": "did",
        "PastParticiple": "done",
        "Μετάφραση": "κάνω"
    }, {
        "Infinitive": "draw",
        "SimplePast": "drew",
        "PastParticiple": "drawn",
        "Μετάφραση": "τραβώ"
    }, {
        "Infinitive": "dream",
        "SimplePast": "dreamed, dreamt",
        "PastParticiple": "dreamed, dreamt",
        "Μετάφραση": "ονειρεύομαι"
    }, {
        "Infinitive": "drive",
        "SimplePast": "drove",
        "PastParticiple": "driven",
        "Μετάφραση": "οδηγώ"
    }, {
        "Infinitive": "drink",
        "SimplePast": "drank",
        "PastParticiple": "drunk",
        "Μετάφραση": "πίνω"
    }, {
        "Infinitive": "dwell",
        "SimplePast": "dwelt",
        "PastParticiple": "dwelt",
        "Μετάφραση": "ζω"
    }, {
        "Infinitive": "eat",
        "SimplePast": "ate",
        "PastParticiple": "eaten",
        "Μετάφραση": "φάω"
    }, {
        "Infinitive": "fall",
        "SimplePast": "fell",
        "PastParticiple": "fallen",
        "Μετάφραση": "πέφτω"
    }, {
        "Infinitive": "feed",
        "SimplePast": "fed",
        "PastParticiple": "fed",
        "Μετάφραση": "τρέφομαι"
    }, {
        "Infinitive": "feel",
        "SimplePast": "felt",
        "PastParticiple": "felt",
        "Μετάφραση": "αισθάνομαι"
    }, {
        "Infinitive": "fight",
        "SimplePast": "fought",
        "PastParticiple": "fought",
        "Μετάφραση": "παλεύω"
    }, {
        "Infinitive": "find",
        "SimplePast": "found",
        "PastParticiple": "found",
        "Μετάφραση": "βρίσκω"
    }, {
        "Infinitive": "flee",
        "SimplePast": "fled",
        "PastParticiple": "fled",
        "Μετάφραση": "το σκάω"
    }, {
        "Infinitive": "fling",
        "SimplePast": "flung",
        "PastParticiple": "flung",
        "Μετάφραση": "εκσφενδονίζομαι"
    }, {
        "Infinitive": "fly",
        "SimplePast": "flew",
        "PastParticiple": "flown",
        "Μετάφραση": "ίπταμαι"
    }, {
        "Infinitive": "forbid",
        "SimplePast": "forbade",
        "PastParticiple": "forbidden",
        "Μετάφραση": "απαγορεύω"
    }, {
        "Infinitive": "freeze",
        "SimplePast": "froze",
        "PastParticiple": "frozen",
        "Μετάφραση": "παγώνω"
    }, {
        "Infinitive": "get",
        "SimplePast": "got",
        "PastParticiple": "gotten",
        "Μετάφραση": "παίρνω"
    }, {
        "Infinitive": "gild",
        "SimplePast": "gilt",
        "PastParticiple": "gilt",
        "Μετάφραση": "επιχρυσώ"
    }, {
        "Infinitive": "give",
        "SimplePast": "gave",
        "PastParticiple": "given",
        "Μετάφραση": "δίνω"
    }, {
        "Infinitive": "go",
        "SimplePast": "went",
        "PastParticiple": "gone",
        "Μετάφραση": "πηγαίνω"
    }, {
        "Infinitive": "grind",
        "SimplePast": "ground",
        "PastParticiple": "ground",
        "Μετάφραση": "αλέθω"
    }, {
        "Infinitive": "grow",
        "SimplePast": "grew",
        "PastParticiple": "grown",
        "Μετάφραση": "μεγαλώνω"
    }, {
        "Infinitive": "hang",
        "SimplePast": "hung",
        "PastParticiple": "hung",
        "Μετάφραση": "κρεμώ"
    }, {
        "Infinitive": "have",
        "SimplePast": "had",
        "PastParticiple": "had",
        "Μετάφραση": "έχω"
    }, {
        "Infinitive": "hear",
        "SimplePast": "heard",
        "PastParticiple": "heard",
        "Μετάφραση": "ακούω"
    }, {
        "Infinitive": "hide",
        "SimplePast": "hid",
        "PastParticiple": "hidden",
        "Μετάφραση": "κρύβω"
    }, {
        "Infinitive": "hit",
        "SimplePast": "hit",
        "PastParticiple": "hit",
        "Μετάφραση": "χτυπώ"
    }, {
        "Infinitive": "hold",
        "SimplePast": "held",
        "PastParticiple": "held",
        "Μετάφραση": "κρατώ"
    }, {
        "Infinitive": "hurt",
        "SimplePast": "hurt",
        "PastParticiple": "hurt",
        "Μετάφραση": "πληγώνω"
    }, {
        "Infinitive": "inlay",
        "SimplePast": "inlaid",
        "PastParticiple": "inlaid",
        "Μετάφραση": "ψηφίδω"
    }, {
        "Infinitive": "interweave",
        "SimplePast": "interwoven",
        "PastParticiple": "interwoven",
        "Μετάφραση": "διαπλέκω"
    }, {
        "Infinitive": "keep",
        "SimplePast": "kept",
        "PastParticiple": "kept",
        "Μετάφραση": "διατηρώ"
    }, {
        "Infinitive": "kneel",
        "SimplePast": "knelt, kneeled",
        "PastParticiple": "knelt, kneeled",
        "Μετάφραση": "γονατίζω"
    }, {
        "Infinitive": "know",
        "SimplePast": "knew",
        "PastParticiple": "known",
        "Μετάφραση": "ξέρω"
    }, {
        "Infinitive": "knit",
        "SimplePast": "knit, knitted",
        "PastParticiple": "knit, knitted",
        "Μετάφραση": "πλέκω"
    }, {
        "Infinitive": "lade",
        "SimplePast": "laded",
        "PastParticiple": "laded",
        "Μετάφραση": "φορτώνω"
    }, {
        "Infinitive": "lay",
        "SimplePast": "laid",
        "PastParticiple": "laid",
        "Μετάφραση": "θέτω"
    }, {
        "Infinitive": "lead",
        "SimplePast": "led",
        "PastParticiple": "led",
        "Μετάφραση": "ηγούμαι"
    }, {
        "Infinitive": "lean",
        "SimplePast": "leaned",
        "PastParticiple": "leaned",
        "Μετάφραση": "στηρίζομαι"
    }, {
        "Infinitive": "leap",
        "SimplePast": "leaded",
        "PastParticiple": "leaded",
        "Μετάφραση": "πηδώ"
    }, {
        "Infinitive": "learn",
        "SimplePast": "learned, learnt",
        "PastParticiple": "learned, learnt",
        "Μετάφραση": "μαθαίνω"
    }, {
        "Infinitive": "leave",
        "SimplePast": "left",
        "PastParticiple": "left",
        "Μετάφραση": "αφήνω"
    }, {
        "Infinitive": "lend",
        "SimplePast": "lent",
        "PastParticiple": "lent",
        "Μετάφραση": "δανείζουν"
    }, {
        "Infinitive": "let",
        "SimplePast": "let",
        "PastParticiple": "let",
        "Μετάφραση": "επιτρέπω"
    }, {
        "Infinitive": "lie",
        "SimplePast": "lay",
        "PastParticiple": "lain",
        "Μετάφραση": "ψεύδομαι"
    }, {
        "Infinitive": "light",
        "SimplePast": "lighted, lit",
        "PastParticiple": "lighted, lit",
        "Μετάφραση": "φωτίζω"
    }, {
        "Infinitive": "lose",
        "SimplePast": "lost",
        "PastParticiple": "lost",
        "Μετάφραση": "χάνω"
    }, {
        "Infinitive": "make",
        "SimplePast": "made",
        "PastParticiple": "made",
        "Μετάφραση": "κάνω"
    }, {
        "Infinitive": "mean",
        "SimplePast": "meant",
        "PastParticiple": "meant",
        "Μετάφραση": "εννοώ"
    }, {
        "Infinitive": "meet",
        "SimplePast": "met",
        "PastParticiple": "met",
        "Μετάφραση": "συναντώ"
    }, {
        "Infinitive": "misspell",
        "SimplePast": "misspelt",
        "PastParticiple": "misspelt",
        "Μετάφραση": "ανορθογραφώ"
    }, {
        "Infinitive": "mislead",
        "SimplePast": "misled",
        "PastParticiple": "misled",
        "Μετάφραση": "mislead"
    }, {
        "Infinitive": "mow",
        "SimplePast": "mowed",
        "PastParticiple": "mown",
        "Μετάφραση": "θερίζω"
    }, {
        "Infinitive": "pay",
        "SimplePast": "paid",
        "PastParticiple": "paid",
        "Μετάφραση": "πληρώνω"
    }, {
        "Infinitive": "prove",
        "SimplePast": "proved",
        "PastParticiple": "proven, proved",
        "Μετάφραση": "αποδείχθνω"
    }, {
        "Infinitive": "put",
        "SimplePast": "put",
        "PastParticiple": "put",
        "Μετάφραση": "βάλλω"
    }, {
        "Infinitive": "quit",
        "SimplePast": "quit",
        "PastParticiple": "quit",
        "Μετάφραση": "παραιτώ"
    }, {
        "Infinitive": "read",
        "SimplePast": "read",
        "PastParticiple": "read",
        "Μετάφραση": "διαβάζω"
    }, {
        "Infinitive": "rid",
        "SimplePast": "rid",
        "PastParticiple": "rid",
        "Μετάφραση": "απαλλάσσω"
    }, {
        "Infinitive": "ride",
        "SimplePast": "rode",
        "PastParticiple": "ridden",
        "Μετάφραση": "ιππεύω"
    }, {
        "Infinitive": "ring",
        "SimplePast": "rang",
        "PastParticiple": "rung",
        "Μετάφραση": "κουδουνίζω"
    }, {
        "Infinitive": "rise",
        "SimplePast": "rose",
        "PastParticiple": "risen",
        "Μετάφραση": "ανατέλλω"
    }, {
        "Infinitive": "run",
        "SimplePast": "ran",
        "PastParticiple": "run",
        "Μετάφραση": "τρέχω"
    }, {
        "Infinitive": "say",
        "SimplePast": "said",
        "PastParticiple": "said",
        "Μετάφραση": "λέω"
    }, {
        "Infinitive": "see",
        "SimplePast": "saw",
        "PastParticiple": "seen",
        "Μετάφραση": "βλέπω"
    }, {
        "Infinitive": "seek",
        "SimplePast": "sought",
        "PastParticiple": "sought",
        "Μετάφραση": "αναζητητώ"
    }, {
        "Infinitive": "sell",
        "SimplePast": "sold",
        "PastParticiple": "sold",
        "Μετάφραση": "πωλώ"
    }, {
        "Infinitive": "send",
        "SimplePast": "sent",
        "PastParticiple": "sent",
        "Μετάφραση": "στέλνω"
    }, {
        "Infinitive": "set",
        "SimplePast": "set",
        "PastParticiple": "set",
        "Μετάφραση": "τοποθετώ"
    }, {
        "Infinitive": "sew",
        "SimplePast": "sewed",
        "PastParticiple": "sewed, sewn",
        "Μετάφραση": "ράβω"
    }, {
        "Infinitive": "shake",
        "SimplePast": "shook",
        "PastParticiple": "shaken",
        "Μετάφραση": "κουνάω"
    }, {
        "Infinitive": "shed",
        "SimplePast": "shed",
        "PastParticiple": "shed",
        "Μετάφραση": "χύνω"
    }, {
        "Infinitive": "shine",
        "SimplePast": "shone",
        "PastParticiple": "shone",
        "Μετάφραση": "λάμπω"
    }, {
        "Infinitive": "shoot",
        "SimplePast": "shot",
        "PastParticiple": "shot",
        "Μετάφραση": "πυροβολώ"
    }, {
        "Infinitive": "show",
        "SimplePast": "showed",
        "PastParticiple": "showed, shown",
        "Μετάφραση": "δείχνω"
    }, {
        "Infinitive": "shrink",
        "SimplePast": "shrank",
        "PastParticiple": "shrunk",
        "Μετάφραση": "συρρικνώνω"
    }, {
        "Infinitive": "shrive",
        "SimplePast": "shrove, shrived",
        "PastParticiple": "shrived",
        "Μετάφραση": "εξομολογώ"
    }, {
        "Infinitive": "shut",
        "SimplePast": "shut",
        "PastParticiple": "shut",
        "Μετάφραση": "κλείνω"
    }, {
        "Infinitive": "sing",
        "SimplePast": "sang",
        "PastParticiple": "sung",
        "Μετάφραση": "τραγουδώ"
    }, {
        "Infinitive": "sink",
        "SimplePast": "sank",
        "PastParticiple": "sunk",
        "Μετάφραση": "βουλιάζω"
    }, {
        "Infinitive": "sit",
        "SimplePast": "sat",
        "PastParticiple": "sat",
        "Μετάφραση": "κάθομαι"
    }, {
        "Infinitive": "sleep",
        "SimplePast": "slept",
        "PastParticiple": "slept",
        "Μετάφραση": "κοιμάμαι"
    }, {
        "Infinitive": "slide",
        "SimplePast": "slid",
        "PastParticiple": "slid",
        "Μετάφραση": "γλιστρώ"
    }, {
        "Infinitive": "sling",
        "SimplePast": "slung",
        "PastParticiple": "slung",
        "Μετάφραση": "εκδφενδονίζω"
    }, {
        "Infinitive": "slit",
        "SimplePast": "slit",
        "PastParticiple": "slit",
        "Μετάφραση": "σχίζω"
    }, {
        "Infinitive": "smell",
        "SimplePast": "smelt",
        "PastParticiple": "smelt",
        "Μετάφραση": "μυρίζω"
    }, {
        "Infinitive": "sow",
        "SimplePast": "sowed",
        "PastParticiple": "sown, sowed",
        "Μετάφραση": "σπέρνω"
    }, {
        "Infinitive": "speak",
        "SimplePast": "spoke",
        "PastParticiple": "spoken",
        "Μετάφραση": "μιλώ"
    }, {
        "Infinitive": "speed",
        "SimplePast": "sped",
        "PastParticiple": "sped",
        "Μετάφραση": "επιταχύνω"
    }, {
        "Infinitive": "spell",
        "SimplePast": "spelt",
        "PastParticiple": "spelt",
        "Μετάφραση": "συλλαβίζω"
    }, {
        "Infinitive": "spend",
        "SimplePast": "spent",
        "PastParticiple": "spent",
        "Μετάφραση": "ξοδεύω"
    }, {
        "Infinitive": "spill",
        "SimplePast": "spilt",
        "PastParticiple": "spilt",
        "Μετάφραση": "χύνω"
    }, {
        "Infinitive": "spin",
        "SimplePast": "spun",
        "PastParticiple": "spun",
        "Μετάφραση": "περιστρέφω"
    }, {
        "Infinitive": "spit",
        "SimplePast": "spat",
        "PastParticiple": "spat",
        "Μετάφραση": "φτύνω, σουφλίζω"
    }, {
        "Infinitive": "split",
        "SimplePast": "split",
        "PastParticiple": "split",
        "Μετάφραση": "χωρίζω"
    }, {
        "Infinitive": "spoil",
        "SimplePast": "spoilt",
        "PastParticiple": "spoilt",
        "Μετάφραση": "κακομαθαίνω"
    }, {
        "Infinitive": "spread",
        "SimplePast": "spread",
        "PastParticiple": "spread",
        "Μετάφραση": "διαδίδω"
    }, {
        "Infinitive": "spring",
        "SimplePast": "sprang, sprung",
        "PastParticiple": "sprung",
        "Μετάφραση": "αναπηδώ"
    }, {
        "Infinitive": "stand",
        "SimplePast": "stood",
        "PastParticiple": "stood",
        "Μετάφραση": "στέκομαι"
    }, {
        "Infinitive": "steal",
        "SimplePast": "stole",
        "PastParticiple": "stolen",
        "Μετάφραση": "κλέβω"
    }, {
        "Infinitive": "stick",
        "SimplePast": "stuck",
        "PastParticiple": "stuck",
        "Μετάφραση": "κολλώ"
    }, {
        "Infinitive": "sting",
        "SimplePast": "stung",
        "PastParticiple": "stung",
        "Μετάφραση": "τσιμπώ"
    }, {
        "Infinitive": "stride",
        "SimplePast": "strode",
        "PastParticiple": "stridden",
        "Μετάφραση": "βαδίζω με μεγάλα βήματα"
    }, {
        "Infinitive": "strike",
        "SimplePast": "struck",
        "PastParticiple": "struck",
        "Μετάφραση": "κτυπώ"
    }, {
        "Infinitive": "string",
        "SimplePast": "strung",
        "PastParticiple": "strung",
        "Μετάφραση": "δένω"
    }, {
        "Infinitive": "swear",
        "SimplePast": "swore",
        "PastParticiple": "sworn",
        "Μετάφραση": "ορκίζομαι"
    }, {
        "Infinitive": "sweep",
        "SimplePast": "swept",
        "PastParticiple": "swept",
        "Μετάφραση": "σκούπιζω"
    }, {
        "Infinitive": "swim",
        "SimplePast": "swam",
        "PastParticiple": "swum",
        "Μετάφραση": "κολυμπώ"
    }, {
        "Infinitive": "swing",
        "SimplePast": "swung",
        "PastParticiple": "swung",
        "Μετάφραση": "κουνώ"
    }, {
        "Infinitive": "take",
        "SimplePast": "took",
        "PastParticiple": "taken",
        "Μετάφραση": "λαμβάνω"
    }, {
        "Infinitive": "teach",
        "SimplePast": "taught",
        "PastParticiple": "taught",
        "Μετάφραση": "διδάσκω"
    }, {
        "Infinitive": "tear",
        "SimplePast": "tore",
        "PastParticiple": "torn",
        "Μετάφραση": "σχίζω"
    }, {
        "Infinitive": "tell",
        "SimplePast": "told",
        "PastParticiple": "told",
        "Μετάφραση": "λέγω"
    }, {
        "Infinitive": "think",
        "SimplePast": "thought",
        "PastParticiple": "thought",
        "Μετάφραση": "νομίζω"
    }, {
        "Infinitive": "throw",
        "SimplePast": "threw",
        "PastParticiple": "thrown",
        "Μετάφραση": "ρίπτω"
    }, {
        "Infinitive": "thrust",
        "SimplePast": "thrust",
        "PastParticiple": "thrust",
        "Μετάφραση": "ωθώ"
    }, {
        "Infinitive": "tread",
        "SimplePast": "trod",
        "PastParticiple": "trodden, trod",
        "Μετάφραση": "πατώ"
    }, {
        "Infinitive": "understand",
        "SimplePast": "understood",
        "PastParticiple": "understood",
        "Μετάφραση": "καταλαβαίνω"
    }, {
        "Infinitive": "wake",
        "SimplePast": "woke",
        "PastParticiple": "woken",
        "Μετάφραση": "ξυπνάω"
    }, {
        "Infinitive": "wear",
        "SimplePast": "wore",
        "PastParticiple": "worn",
        "Μετάφραση": "φορώ"
    }, {
        "Infinitive": "weave",
        "SimplePast": "wove",
        "PastParticiple": "weaved",
        "Μετάφραση": "υφαίνω"
    }, {
        "Infinitive": "wed",
        "SimplePast": "wed",
        "PastParticiple": "wed",
        "Μετάφραση": "παντρεύομαι"
    }, {
        "Infinitive": "weep",
        "SimplePast": "wept",
        "PastParticiple": "wept",
        "Μετάφραση": "κλαίω"
    }, {
        "Infinitive": "wet",
        "SimplePast": "wet",
        "PastParticiple": "wet",
        "Μετάφραση": "υγραίνω"
    }, {
        "Infinitive": "win",
        "SimplePast": "won",
        "PastParticiple": "won",
        "Μετάφραση": "κερδίζω"
    }, {
        "Infinitive": "wind",
        "SimplePast": "wound",
        "PastParticiple": "wound",
        "Μετάφραση": "περιτυλίσσω"
    }, {
        "Infinitive": "wring",
        "SimplePast": "wrung",
        "PastParticiple": "wrung",
        "Μετάφραση": "στραγγίζω"
    }, {
        "Infinitive": "write",
        "SimplePast": "wrote",
        "PastParticiple": "written",
        "Μετάφραση": "γράφω"
    }
]